### ISSUE TITLE
Playbook Issue - Cloudflare

### ISSUE THREAD

**Issue by jc1396** [guidepointsecurity/RedCommander#1]
Any idea why the install keeps failing at this point?

___________________________________________________
< TASK 50/3 [Adding CloudFlare Records for Domains] >
 ---------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /opt/RedCommander/tasks/web_rdir/cloudflare.yml:3
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1600547516.1146615-399592-81350709199337 && echo ansible-tmp-1600547516.1146615-399592-81350709199337="` echo /root/.ansible/tmp/ansible-tmp-1600547516.1146615-399592-81350709199337 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/net_tools/cloudflare_dns.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-398472oxdo6sx2/tmp0rdhdo1f TO /root/.ansible/tmp/ansible-tmp-1600547516.1146615-399592-81350709199337/AnsiballZ_cloudflare_dns.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1600547516.1146615-399592-81350709199337/ /root/.ansible/tmp/ansible-tmp-1600547516.1146615-399592-81350709199337/AnsiballZ_cloudflare_dns.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1600547516.1146615-399592-81350709199337/AnsiballZ_cloudflare_dns.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1600547516.1146615-399592-81350709199337/ > /dev/null 2>&1 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1600547517.2712681-399592-86329928516922 && echo ansible-tmp-1600547517.2712681-399592-86329928516922="` echo /root/.ansible/tmp/ansible-tmp-1600547517.2712681-399592-86329928516922 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/net_tools/cloudflare_dns.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-398472oxdo6sx2/tmp9wmg3a_e TO /root/.ansible/tmp/ansible-tmp-1600547517.2712681-399592-86329928516922/AnsiballZ_cloudflare_dns.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1600547517.2712681-399592-86329928516922/ /root/.ansible/tmp/ansible-tmp-1600547517.2712681-399592-86329928516922/AnsiballZ_cloudflare_dns.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1600547517.2712681-399592-86329928516922/AnsiballZ_cloudflare_dns.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1600547517.2712681-399592-86329928516922/ > /dev/null 2>&1 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1600547517.738528-399592-142328937125563 && echo ansible-tmp-1600547517.738528-399592-142328937125563="` echo /root/.ansible/tmp/ansible-tmp-1600547517.738528-399592-142328937125563 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/net_tools/cloudflare_dns.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-398472oxdo6sx2/tmp8g3wuitd TO /root/.ansible/tmp/ansible-tmp-1600547517.738528-399592-142328937125563/AnsiballZ_cloudflare_dns.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1600547517.738528-399592-142328937125563/ /root/.ansible/tmp/ansible-tmp-1600547517.738528-399592-142328937125563/AnsiballZ_cloudflare_dns.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1600547517.738528-399592-142328937125563/AnsiballZ_cloudflare_dns.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1600547517.738528-399592-142328937125563/ > /dev/null 2>&1 && sleep 0'
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=44   changed=3    unreachable=0    failed=1    rescued=0    ignored=0

**Comment by offsecginger** [comment]
Based on the data you provided, the only thing I can think of is that you
haven't manually added your domains to cloudflare yet.

**Comment by jc1396** [comment]
I have added the domain to cloudflare and I can also see the new A records added. (c2-dns, c2-https, redelk).  Not sure what to do at this point.

**Comment by offsecginger** [comment]
Interesting,

Can you paste your -vvvv output (please redact your sensitive information.)

W. Alexander Williams, OSCP, GXPN
wayneaswilliams@gmail.com
1 (919) 224-9123
Resume <http://wayneaswilliams.com/resume>

**Comment by offsecginger** [comment]
Interesting, Can you paste your -vvvv output (please redact your sensitive information.)
